// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransportationSystem.Data;

#nullable disable

namespace TransportationSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransportationSystem.Models.BusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A bus designed for urban transport.",
                            Name = "City Bus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A bus designed for long-distance travel between cities.",
                            Name = "Intercity Bus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A high-end bus with comfortable seating and amenities.",
                            Name = "Luxury Coach"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
